#!/usr/bin/env bash
# Install nginx and set homepage to Hello World!

sudo apt update
sudo apt install nginx -y
sudo echo "Hello world!" | sudo tee /var/www/html/index.html
sudo rm /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx reload
