#!/usr/bin/env bash
# Install nginx and set homepage to Hello World!

sudo apt update
sudo apt install nginx -y

mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

sudo echo "Hello World!" | sudo tee /var/www/html/index.html
SERVER="server {
	  listen 80;
	  root /var/www/html;
	  index index.html;

	  location / {
	    try_files \$uri \$uri/ =404;
          }
  	if (\$request_filename ~ redirect_me){
		rewrite ^ https://nginx.org permanent;
	}
}"

sudo bash -c "echo -e '$SERVER' | sudo tee /etc/nginx/sites-enabled/default"

sudo service nginx start
sudo nginx -s reload
