#!/usr/bin/env bash
# Install nginx and set error page!

sudo apt update
sudo apt install nginx -y

mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
SERVER="server {
	  listen 80;
	  root /var/www/html;
	  index index.html;

	  location / {
	    try_files \$uri \$uri/ =404;
          }
  	  if (\$request_filename ~ redirect_me){
		rewrite ^ https://nginx.org permanent;
	  }
	  error_page 404 /404.html;
	  location = /404.html {
  	    internal;
  	  }
}"

sudo bash -c "echo -e '$SERVER' | sudo tee /etc/nginx/sites-enabled/default"
sudo sed -i 's/http {/http { \n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf

sudo service nginx start
sudo nginx -s reload
