#!/bin/bash
# Define a function to remove the PID file and terminate the script


cleanup() {
    rm -f /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap 'cleanup' SIGTERM SIGQUIT
done
