#!/bin/bash
# Define a function to remove the PID file and terminate the script


cleanup() {
    echo "Removing PID file and terminating the script..."
    rm -f /var/run/myscript.pid
    exit
}

trap 'cleanup' SIGTERM SIGQUIT

trap 'echo "Y U no love me?!"' SIGINT

trap 'echo "I hate the kill command"' SIGTERM

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
