#!/usr/bin/env bash
# This script is displaying "Best School" 9 times
# It says Hi once

count=0
while (("$count" <= 10))
do
  if (("$count" == 9)) 
  then
    echo "Hi"
  else
    echo "Best School" 
  fi
  ((count++))
done
